# Generated by Django 3.0 on 2023-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_recipe_saved'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_saved', to='catalog.Recipe'),
        ),
    ]
