# Generated by Django 4.2.8 on 2024-06-15 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="saved_recipes",
        ),
    ]
