# Generated by Django 4.2.8 on 2024-06-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_recipestatistic_created_at_usersavedrecipe"),
        ("users", "0005_user_saved_recipes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="saved_recipes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="users_saved",
                through="catalog.UserSavedRecipe",
                to="catalog.recipe",
            ),
        ),
    ]
