# Generated by Django 4.2.8 on 2025-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_recipeview_user_alter_recipe_year"),
        ("users", "0006_alter_user_saved_recipes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="saved_recipes",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_saved",
                through="catalog.UserSavedRecipe",
                to="catalog.recipe",
            ),
        ),
    ]
