# Generated by Django 3.0 on 2023-11-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20231112_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolink',
            old_name='video_link',
            new_name='url',
        ),
    ]
