# Generated by Django 3.0 on 2023-11-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20231112_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='saved',
        ),
    ]
