# Generated by Django 4.2.8 on 2023-12-12 19:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
