# Generated by Django 4.2.8 on 2024-06-15 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_recipestatistic_created_at_usersavedrecipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestatistic",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
