# Generated by Django 4.2.8 on 2024-06-15 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_recipestatistic_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="catalog.recipe",
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "ip_address")},
            },
        ),
    ]
