# Generated by Django 4.2.8 on 2025-05-11 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0012_recipeview_user_alter_recipe_year"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipeview",
            unique_together={("recipe", "user", "ip_address")},
        ),
    ]
